## 手写Promise

基于原生 JS 实现 Promise（遵循的是 Promise A Plus 规范）
[https://promisesaplus.com/](https://promisesaplus.com/)

回调函数：把一个函数 A 作为值，传递到另外一个执行的函数 B 中，在 B 中可以把 A 执行

- 执行 0 ~ N 次
- 改变函数中的 this
- 可以给回调函数传递参数
- 接收函数的返回值

先看一下 Promise 具有的方法：

![](https://gitee.com/lilyn/pic/raw/master/js-img/20210910105320.png)

Promise 原理：

1. 首先会给当前实例增加状态（默认是 pending 等待态）和两个事件池 成功的事件池和失败的事件池（用来存放 then 中还不知道实例状态的事件）

2. 其次最重要的就是 Promise 内部传递的 executor 函数，此函数会立即执行并会传递两个回调函数 resolve 和 reject，当执行任何一个回调函数时，都会做两件事情：**更改状态、发布对应事件池的状态方法** 

   注意：更改完状态就不能再更改了（是 pending 才会改状态）；执行回调函数时如果基于 then 存储过方法，依次通知对应状态的事件池方法执行，且执行是异步的微任务

3. new Promise 会创造实例，实例可以调用其所属类原型的方法，之后重构了一下 Promise 构造函数原型上的方法

4. then 方法返回一个全新的 Promise 实例，有两种情况：

   - 如果已经知道对应实例的状态，则创建一个异步的微任务，后期执行对应的 onFulfilled/onRejected
   - 如果此时还不知道实例状态，就先把 onFulfilled/onRejected 存储起来，后期更改其状态之后，再通知方法执行即可，也是异步微任务

   注意：返回新的 Promise 实例不能和执行结果是同一个 `let p2 = p1.then(() => p2)` 

   如何验证返回的是否是一个新的 Promise 实例：类型是 object 或 function 且它得具有 then 方法（是一个函数）。如果返回的不是 Promise 实例，且执行没有报错，则返回一个成功的 Promise 实例

5. 如果 then 中的某个回调函数（resolve、reject）不设置，其默认具备穿透性，顺延到下一个 then 中的同状态的方法上

   如果没有传 onFulfilled 或 onRejected，就给对应的默认传递 resolve 或 reject 即可

6. catch 相当于调用 then，第一个参数不写，第二个参数传递错误原因

7. all 传入的必须是一个数组，如果数组中某一项不是 Promise 实例，需要把它转换为成功的 Promise 实例。之后把每一项依次执行，只要有一项失败返回就是失败的，必须全部成功才是成功

   注意：返回结果的顺序跟传入的顺序一致（不能使用 push，因为不能确定谁先到，需要使用索引）

需要注意的点：

- Promise 是一个构造函数，需要 new 执行
- Promise 参数必须是一个函数
- Promise then 里的方法实际上是异步的微任务，可以基于 queueMicrotask 去创造异步的微任务（兼容性差）；这里采用基于定时器创造一个异步的宏任务，来模拟微任务 

```js
;(function () {
  function Promise(executor) {
    var self = this,
      change
    // 必须new执行
    if (!(self instanceof Promise)) throw new TypeError('undefined is not a promise')
    // executor必须是一个函数
    if (typeof executor !== 'function') throw new TypeError('Promise resolver ' + executor + ' is not a function')

    // 实例具备的属性，状态和结果
    self.state = 'pending'
    self.result = undefined
    self.onFulfilledCallbacks = []
    self.onRejectedCallbacks = []

    // 修改实例的状态
    change = function change(state, result) {
      if (self.state !== 'pending') return
      self.state = state
      self.result = result
      // 创建异步微任务，通知集合中存储的方法执行（前提：集合中有东西才执行）
      var callbacks = state === 'fulfilled' ? self.onFulfilledCallbacks : self.onRejectedCallbacks,
        i = 0,
        len = callbacks.length,
        callback
      if (callbacks.length > 0) {
        setTimeout(function () {
          for (; i < len; i++) {
            callback = callbacks[i]
            if (typeof callback === 'function') callback(result)
          }
        }, 0)
      }
    }

    // new Promise的时候会立即执行executor函数
    try {
      executor(
        function resolve(result) {
          change('fulfilled', result)
        },
        function reject(reason) {
          change('rejected', reason)
        }
      )
    } catch (error) {
      // 执行executor报错，实例也是失败的状态
      change('rejected', error)
    }
  }

  // 验证是否为Promise
  function isPromise(x) {
    if (x == null) return false
    if (/^(object|function)$/i.test(typeof x)) {
      if (typeof x.then === 'function') {
        return true
      }
    }
    return false
  }

  // 处理onFulfilled/onRejected方法执行返回结果的处理
  function handle(promiseNew, x, resolve, reject) {
    if (x === promiseNew) throw new TypeError('TypeError: Chaining cycle detected for promise #<Promise>')
    if (isPromise(x)) {
      try {
        x.then(resolve, reject)
      } catch (err) {
        reject(err)
      }
      return
    }
    // 返回不是promise实例，而且执行没有报错，则promiseNew一定是成功的，x是它的结果
    resolve(x)
  }

  Promise.prototype = {
    constructor: Promise,
    self: true,
    then: function (onFulfilled, onRejected) {
      var self = this,
        promiseNew,
        x
      if (typeof onFulfilled !== 'function') {
        onFulfilled = function onFulfilled(result) {
          return result
        }
      }
      if (typeof onRejected !== 'function') {
        onRejected = function onRejected(reason) {
          throw reason
        }
      }
      promiseNew = new Promise(function (resolve, reject) {
        // resolve reject可以设置返回的@TP（新promise实例是成功还是失败以及结果等）
        // 但是执行哪个方法，由监听onFulfilled/onRejected方法报错以及返回值来决定
        switch (self.state) {
          case 'fulfilled':
            setTimeout(function () {
              try {
                x = onFulfilled(self.result)
                handle(promiseNew, x, resolve, reject)
              } catch (err) {
                reject(err)
              }
            }, 0)
            break
          case 'rejected':
            setTimeout(function () {
              try {
                x = onRejected(self.result)
                handle(promiseNew, x, resolve, reject)
              } catch (err) {
                reject(err)
              }
            }, 0)
            break
          default:
            self.onFulfilledCallbacks.push(function (result) {
              try {
                x = onFulfilled(result)
                handle(promiseNew, x, resolve, reject)
              } catch (err) {
                reject(err)
              }
            })
            self.onRejectedCallbacks.push(function (reason) {
              try {
                x = onRejected(reason)
                handle(promiseNew, x, resolve, reject)
              } catch (err) {
                reject(err)
              }
            })
        }
      })
      return promiseNew
    },
    catch: function (onRejected) {
      return this.then(null, onRejected)
    },
  }
  if (typeof Symbol !== 'undefined') Promise.prototype[Symbol.toStringTag] = 'Promise'

  // 普通对象：私有静态方法
  Promise.all = function all(promises) {
    var promiseNew,
      results = [],
      n = 0
    if (!Array.isArray(promises)) throw new TypeError(promises + ' is not iterable')
    // 控制集合中的每一项都是Promise实例
    promises = promises.map(function (promise) {
      if (!isPromise(promise)) return Promise.resolve(promise)
      return promise
    })
    promiseNew = new Promise(function (resolve, reject) {
      promises.forEach(function (promise, index) {
        promise
          .then(function (result) {
            // result存储的是当前迭代这一项的成功结果
            n++
            results[index] = result
            // 都处理成功
            if (n >= promises.length) resolve(results)
          })
          .catch(function (reason) {
            // 只要有一项失败，整体就是失败
            reject(reason)
          })
      })
    })
    return promiseNew
  }
  Promise.resolve = function resolve(result) {
    return new Promise(function (resolve) {
      resolve(result)
    })
  }
  Promise.reject = function reject(reason) {
    return new Promise(function (_, reject) {
      reject(reason)
    })
  }

  /* 暴露API */
  if (typeof window !== 'undefined') window.Promise = Promise
  // if (typeof module === 'object' && typeof module.exports === 'object') module.exports = Promise
})()

let p1 = new Promise(function (resolve, reject) {
  Math.random() < 0.6 ? resolve('OK') : reject('NO')
})
// try catch 一般情况下是无法捕捉到异步任务执行报错信息
let p2 = p1.then(function (result) {
  console.log('成功', result)
  return 200
})

let p3 = p2.then(
  function (result) {
    console.log('成功', result)
  },
  function (reason) {
    console.log('失败', reason)
  }
)

let p4 = Promise.resolve(10)
let p5 = new Promise(resolve => {
  setTimeout(() => {
    resolve(20)
  }, 1000)
})
let p6 = 30
Promise.all([p4, p5, p6])
  .then(results => {
    console.log('成功', results)
  })
  .catch(reason => {
    console.log('失败', reason)
  })
```

ES6 方法实现 Promise，可以参考我另外一篇文章 [手撕 Promise（内附then链实现）](https://blog.csdn.net/qq_38689395/article/details/114014869)

